# Fly.io configuration for Academic Project Tracker
app = "academic-project-tracker"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[env]
  FLASK_ENV = "production"

[processes]
  web = "gunicorn --bind 0.0.0.0:5000 main:app"